/* Step 2
Purpose: Inserting the data in to tables in an order
File Usage Instructions: Step 2
1. After executing Database.sql file
2. Now execute Data.sql code as PGScript.*/

-- Inserting data in auth_level table
INSERT INTO auth_level VALUES (0, 'Admin role');
INSERT INTO auth_level VALUES (1, 'General Associate');
INSERT INTO auth_level VALUES (2, 'Instructor');

-- Inserting data in admins table
INSERT INTO admins VALUES ('AP045635', ' Abhi', 'Purella', 'Abhi.Purella@cerner.com', 'ADMIN', 0, false, 'Software Engineer', 'Dev Academy');
INSERT INTO admins VALUES ('WW044343', 'Wuchen', 'Wang', 'Wuchen.Wang@Cerner.com', 'ADMIN', 0, false, 'Software Engineer', 'Cloud Platform Dev');
INSERT INTO admins VALUES ('YG045907', ' Yogesh', 'Ghimire', 'Yogesh.Ghimire@cerner.com', 'ADMIN', 0, false, 'Software Engineer', 'Learning Tech Development');
INSERT INTO admins VALUES ('GK045931', ' Gunjan', 'Kaphle', 'Gunjan.Kaphle@cerner.com', 'ADMIN', 0, false, 'Software Engineer', 'Dev Academy');
INSERT INTO admins VALUES ('RM044127', 'Ram', 'Manickam', 'Ram.Manickam@Cerner.com', 'ADMIN', 0, false, 'Software Engineer', 'Core MSVC Dev');
INSERT INTO admins VALUES ('AM045300', ' Asim', 'Mohammed', 'Asim.Mohammed@cerner.com', 'ADMIN', 0, false, NULL, NULL);

-- Inserting data in category table
INSERT INTO category VALUES (1, 'software', 'development', 1);
INSERT INTO category VALUES (2, 'Security', 'Knowledge of potential vulnerabilities in software, applications, and human error', 1);
INSERT INTO category VALUES (3, 'Languages', 'Knowledge of one or more programming languages', 1);
INSERT INTO category VALUES (4, 'Tools', 'Knowledge of key development tools used at Cerner', 1);
INSERT INTO category VALUES (5, 'Troubleshooting and support', 'Knowledge of best practices for remediating solution problems and support needs', 1);
INSERT INTO category VALUES (6, 'System acumen', 'Knowledge of system, database, and networking administration', 2);
INSERT INTO category VALUES (7, 'Testing', 'Knowledge of static/dynamic testing, box approach testing, testing levels, and testing process', 2);
INSERT INTO category VALUES (8, 'Abilities/Performance', 'Knowledge of scalability, availability, affordability, manageability, installability, reliability, and performance consideration', 2);
INSERT INTO category VALUES (9, 'Documentation and SDLC', 'Knowledge of Cerner''s development lifecycle and documentation approach and relevance to the development cycle', 2);
INSERT INTO category VALUES (10, 'Soft Skills', 'Knowledge of key communication skills and emotional intelligence', 3);
INSERT INTO category VALUES (11, 'Design', 'Knowledge of solution and technical design', 3);
INSERT INTO category VALUES (12, 'Problem Solving', 'Knowledge of key strategies for addressing problems', 3);
INSERT INTO category VALUES (13, 'soft', 'it includes softwares', 3);
INSERT INTO category VALUES (14, 'refactoring', 'Resources useful to refactor code', 3);
INSERT INTO category VALUES (16, 'WBT', 'Web based training', 4);
INSERT INTO category VALUES (17, 'Big Data', 'Learn about large and complex data sets', 4);
INSERT INTO category VALUES (18, 'Java', 'learn about the programming language', 4);
INSERT INTO category VALUES (19, 'Debugging', 'Learn to debug code', 4);
INSERT INTO category VALUES (20, 'Game Development', 'Learn game development on different platforms', 4);
INSERT INTO category VALUES (21, 'JSP', 'Java servlet pages', 4);
INSERT INTO category VALUES (22, 'Apple', 'Study on Apple products', 5);
INSERT INTO category VALUES (23, 'Dell', 'learn on dell products', 5);
INSERT INTO category VALUES (24, 'MS Visio', 'Database Diagrams', 5);
INSERT INTO category VALUES (25, 'Eclipse', 'Learn to use the IDE', 5);
INSERT INTO category VALUES (26, 'Object Oriented Programming ', 'Learn the basics of OOP', 5);

-- Inserting data in type table
INSERT INTO type VALUES ('Youtube', 1);
INSERT INTO type VALUES ('Link', 2);
INSERT INTO type VALUES ('EBook', 3);
INSERT INTO type VALUES ('Online Classroom', 4);
INSERT INTO type VALUES ('Codility', 5);
INSERT INTO type VALUES ('Code Academy', 6);
INSERT INTO type VALUES ('W3Schools', 56);
INSERT INTO type VALUES ('ULearn', 57);
INSERT INTO type VALUES ('sadasd', 58);
INSERT INTO type VALUES ('OfficialWebsite', 59);

-- Inserting data in resource table
ALTER SEQUENCE resource_resource_id_seq RESTART WITH 500;
INSERT INTO resource VALUES (167, 'dot net', 'http://opencsv.sourceforge.net/', 'Apache ', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (168, 'linux', 'http://stackoverflow.com/questions/11839190/how-to-read-next-line-in-txt-file', 'Questions', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (170, 'dot net', 'http://opencsv.sourceforge.net/', 'Apache ', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (171, 'linux', 'http://stackoverflow.com/questions/11839190/how-to-read-next-line-in-txt-file', 'Questions', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (175, 'java', 'http://stackoverflow.com/questions/687833/how-to-get-the-last-value-of-an-arraylist', 'Stack Overflow', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (176, 'dot net', 'http://opencsv.sourceforge.net/', 'Apache ', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (177, 'linux', 'http://stackoverflow.com/questions/11839190/how-to-read-next-line-in-txt-file', 'Questions', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (186, 'test', 'https://www.google.com/', 'test3212', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (188, 'test', 'https://www.yahoo.com/', 'Yahoo', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (189, 'king', 'https://www.yahoo.com/', 'Yahoo', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (190, 'java', 'https://www.yahoo.com/', 'Yahoo', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (249, 'SQL Tutorial', 'http://www.w3schools.com/sql/', 'Basic SQL', 56, 'SV051339', 'Available');
INSERT INTO resource VALUES (193, 'ruby', 'http://www.cnn.com/world', 'outlook', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (194, 'unix', 'http://www.bbc.co.uk/worldserviceradio', 'bbc', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (196, 'ruby', 'http://www.cnn.com/world', 'outlook', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (254, 'CSS Colors', 'http://www.w3schools.com/cssref/css_colors.asp', 'Different colors on CSS', 2, 'SV051339', 'Available');
INSERT INTO resource VALUES (259, 'test', 'https://www.google.com/', 'test', 5, 'SV051339', 'Available');
INSERT INTO resource VALUES (264, 'Java Classpath', 'http://docs.oracle.com/javase/7/docs/technotes/tools/solaris/classpath.html', 'Learn to set classpath variable', 2, 'SV051339', 'Available');
INSERT INTO resource VALUES (24, 'uCern - Rational Requirements Composer', 'https://connect.ucern.com/groups/rational-requirements-composer', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (26, 'uCernWiki - Feature Tracker', 'https://wiki.ucern.com/display/ipfactory/Feature%20Tracker%20FAQs', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (27, 'uCernWiki - Package Tracker', 'https://wiki.ucern.com/display/ipfactory/Package%20Tracker%20FAQs', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (28, 'uCern - Abilities Center', 'https://connect.ucern.com/community/cerner/associates/cernerworks/abl', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (29, 'uCernWiki - Accessibility at Cerner', 'https://wiki.ucern.com/pages/viewpage.action?pageId=1349366808', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (162, 'linux', 'http://stackoverflow.com/questions/11839190/how-to-read-next-line-in-txt-file', 'Questions',  3, 'SV051339', 'Available');
INSERT INTO resource VALUES (164, 'dot net', 'http://opencsv.sourceforge.net/', 'Apache ', 3, 'SV051339', 'Available');
INSERT INTO resource VALUES (165, 'linux', 'http://stackoverflow.com/questions/11839190/how-to-read-next-line-in-txt-file', 'Questions',  3, 'SV051339', 'Available');
INSERT INTO resource VALUES (232, 'ruby', 'http://www.cnn.com/world', 'outlook', 5, 'SV051339', 'Available');
INSERT INTO resource VALUES (237, 'ruby', 'http://www.cnn.com/world', 'outlook', 5, 'SV051339', 'Available');
INSERT INTO resource VALUES (242, 'Spring MVC', 'http://docs.spring.io/spring-framework/docs/2.0.8/reference/mvc.html', 'learn spring mvc framework', 5, 'SV051339', 'Available');
INSERT INTO resource VALUES (226, 'ruby', 'http://www.cnn.com/world', 'outlook', 5, 'SV051339', 'Available');
INSERT INTO resource VALUES (228, 'ruby', 'http://www.cnn.com/world', 'outlook', 5, 'SV051339', 'Available');
INSERT INTO resource VALUES (243, 'ruby', 'http://www.cnn.com/world', 'outlook', 5, 'SV051339', 'Available');
INSERT INTO resource VALUES (248, 'ruby', 'http://www.cnn.com/world', 'outlook', 5, 'SV051339', 'Available');
INSERT INTO resource VALUES (250, 'Bootstrap', 'http://www.w3schools.com/bootstrap/default.asp', 'Basics of bootstrap', 56, 'SV051339', 'Available');
INSERT INTO resource VALUES (260, 'testtuesday', 'https://www.google.com/', 'testtuesday', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (45, 'This is a test', 'http://www.holla.com', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (49, 'Better work', 'http://www.holla.com', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (31, 'uCern - Solution Designer', 'https://connect.ucern.com/community/cerner/associates/engineering/groups/ip-development-solution-designers', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (46, 'This is a test', 'http://www.add.com', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (55, 'SoftwareTesting', 'http://www.tutorialspoint.com/software_testing/', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (61, 'JSP Tutorial', 'http://www.jsptut.com/Scriptlets.jsp', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (63, 'Spring Framework', 'http://www.tutorialspoint.com/spring/spring_web_mvc_framework.htm', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (94, 'dsadad', 'http://www.resource.com', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (156, 'java', 'http://stackoverflow.com/questions/687833/how-to-get-the-last-value-of-an-arraylist', 'Stack Overflow', 3, 'SV051339', 'Available');
INSERT INTO resource VALUES (159, 'linux', 'http://stackoverflow.com/questions/11839190/how-to-read-next-line-in-txt-file', 'Questions', 3, 'SV051339', 'Available');
INSERT INTO resource VALUES (161, 'dot net', 'http://opencsv.sourceforge.net/', 'Apache ', 3, 'SV051339', 'Available');
INSERT INTO resource VALUES (197, 'unix', 'http://www.bbc.co.uk/worldserviceradio', 'bbc', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (217, 'Java Fundamentalss', 'https://jsfiddle.net/', 'Study on the basic hardware devices', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (222, 'https://www.google.com/?gws_rd=ssl', 'https://www.google.com/?gws_rd=ssl,asdasd', 'asdasd,asdasd', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (201, 'Jira', 'https://www.atlassian.com/software/jira', 'Learn to track and maintain stories and tasks', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (208, 'Bootstrap', 'http://www.w3schools.com/bootstrap/default.asp', 'Learn basic bootstrap', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (218, 'Java Fundamentalss', 'https://jsfiddle.net/', 'Study on the basic hardware devices', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (211, 'testThursday', 'https://www.google.com/', 'test01 for delete category', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (216, 'Java Fundamentals', 'https://jsfiddle.net/', 'Study on the basic hardware devices', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (210, 'Java Fundamentals', 'http://www.codejava.net/frameworks/spring/14-tips-for-writing-spring-mvc-controller', 'Learn game development on different platforms', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (30, 'uCernWiki - ProcessIT', 'https://wiki.ucern.com/display/public/processIT/ProcessIT', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (1, 'Health Care Acumen Collaborative', 'https://connect.ucern.com/groups/health-care-acumen-collaborative', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (2, 'Healthcare Industry Overview', 'https://wiki.ucern.com/display/public/AssociateEd/Health+Care+Industry+Overview', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (6, 'Codeacademy - Ruby', 'http://www.codecademy.com/tracks/ruby', 'test_description', 2, 'SV051339', 'Available');
INSERT INTO resource VALUES (7, 'Railsforzombies', 'http://railsforzombies.org/', 'test_description', 2, 'SV051339', 'Available');
INSERT INTO resource VALUES (8, 'Codeschool - Railsforzombies', 'https://www.codeschool.com/courses/rails-for-zombies-redux', 'test_description', 3, 'SV051339', 'Available');
INSERT INTO resource VALUES (9, 'Railscasts', 'http://railscasts.com/', 'test_description', 2, 'SV051339', 'Available');
INSERT INTO resource VALUES (10, 'Udemy - Java', 'https://www.udemy.com/java-tutorial/', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (12, 'Codeacademy - Javascript', 'https://www.codecademy.com/tracks/javascript', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (13, 'Learn JS', 'http://www.learn-js.org/', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (14, 'Learn C#', 'http://www.learncs.org/', 'test_description', 2, 'SV051339', 'Available');
INSERT INTO resource VALUES (16, 'Git Immersion', 'http://gitimmersion.com/index.html', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (17, 'Tutorialspoint - SVN', 'http://www.tutorialspoint.com/svn/', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (18, 'Vogella - Eclipse', 'http://www.vogella.com/tutorials/Eclipse/article.html', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (19, 'Apache Maven Guide', 'http://maven.apache.org/guides/getting-started/maven-in-five-minutes.html', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (20, 'Vogella - Maven', 'http://www.vogella.com/tutorials/Jenkins/article.html', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (21, 'uCern - Testing Center', 'https://connect.ucern.com/groups/ip-development-test-designers', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (22, 'uCern - CCL', 'https://connect.ucern.com/community/cerner/associates/groups/ccl-discern-explorer-client-alpha?view=overview', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (225, 'java', 'https://www.yahoo.com/', 'Yahoo', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (199, 'PHP Fundamentals', 'http://www.w3schools.com/php/default.asp', 'learn basic php', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (209, 'Bootstrap', 'http://www.w3schools.com/bootstrap/default.asp', 'Learn basic bootstrap', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (219, 'Java Fundamentalss', 'https://jsfiddle.net/', 'Study on the basic hardware devices', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (241, 'ruby', 'http://www.cnn.com/world', 'outlook', 5, 'SV051339', 'Available');
INSERT INTO resource VALUES (246, 'ruby', 'http://www.cnn.com/world', 'outlook', 5, 'SV051339', 'Available');
INSERT INTO resource VALUES (230, 'ruby', 'http://www.cnn.com/world', 'outlook',  5, 'SV051339', 'Available');
INSERT INTO resource VALUES (240, 'ruby', 'http://www.cnn.com/world', 'outlook',  5, 'SV051339', 'Available');
INSERT INTO resource VALUES (245, 'ruby', 'http://www.cnn.com/world', 'outlook',  5, 'SV051339', 'Available');
INSERT INTO resource VALUES (224, 'ruby', 'http://www.cnn.com/world', 'outlook',  4, 'SV051339', 'Available');
INSERT INTO resource VALUES (200, 'Ruby on rails', 'https://www.codecademy.com/learn/learn-rails', 'Learn ruby on rails', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (205, 'Jira', 'https://www.atlassian.com/software/jira', 'Learn to track and maintain stories and tasks', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (215, 'ruby', 'http://www.cnn.com/world', 'outlook', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (234, 'java', 'https://www.yahoo.com/', 'Yahoo', 5, 'SV051339', 'Available');
INSERT INTO resource VALUES (239, 'ruby', 'http://www.cnn.com/world', 'outlook', 5, 'SV051339', 'Available');
INSERT INTO resource VALUES (244, 'ruby', 'http://www.cnn.com/world', 'outlook', 5, 'SV051339', 'Available');
INSERT INTO resource VALUES (251, 'The best resource available', 'http://java.com/en/', 'Learn java', 59, 'SV051339', 'Available');
INSERT INTO resource VALUES (256, 'HTML', 'http://www.w3schools.com/html/', 'Learn basic html', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (261, 'testtuesday', 'https://www.google.com/', 'testtuesday', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (95, 'dddd', 'http://www.resource.com', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (115, 'google', 'https://www.google.com/?gws_rd=ssl', 'google', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (120, 'google', 'https://www.google.com/?gws_rd=ssl', 'text', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (114, 'google', 'https://www.google.com/?gws_rd=ssl', 'google', 2, 'SV051339', 'Available');
INSERT INTO resource VALUES (151, 'dot net', 'http://opencsv.sourceforge.net/', 'Apache ',  3, 'SV051339', 'Available');
INSERT INTO resource VALUES (101, 'dsadad', 'http://www.resource.com', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (252, 'CSS Colors', 'http://www.w3schools.com/cssref/css_colors.asp', 'Different colors on CSS', 2, 'SV051339', 'Available');
INSERT INTO resource VALUES (257, 'HTML', 'http://www.w3schools.com/html/', 'Learn basic html', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (102, 'google', 'http://www.google.com', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (103, 'google', 'http://www.googletest.com', 'course for test', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (106, 'google', 'http://www.googletest.com', 'course for test', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (108, 'google', 'http://www.googletest.com', 'course for test', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (262, 'testtuesday', 'https://www.google.com/', 'testtuesday',  1, 'SV051339', 'Available');
INSERT INTO resource VALUES (107, 'google', 'http://www.googletest.com', 'course for test', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (104, 'google', 'http://www.googletest.com', 'course for test', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (109, 'google', 'http://www.googlerishi.com', 'ajaja', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (121, 'JDBC_Spring', 'http://www.mkyong.com/spring/spring-jdbctemplate-querying-examples/', 'jdbc tutorial', 3, 'SV051339', 'Available');
INSERT INTO resource VALUES (112, 'google', 'https://www.google.com/?gws_rd=ssl', 'google', 2, 'SV051339', 'Available');
INSERT INTO resource VALUES (111, 'google', 'http://www.googletest.com', 'course for test', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (132, 'spring', 'http://www.codejava.net/frameworks/spring/14-tips-for-writing-spring-mvc-controller', 'Spring mvc', 2, 'SV051339', 'Available');
INSERT INTO resource VALUES (125, 'link', 'http://www.mkyong.com/spring/spring-jdbctemplate-querying-examples/', 'Google link', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (96, 'dsadad', 'http://www.resource.com', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (98, 'dsadad', 'http://www.resource.com', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (69, 'Software Development Methology', 'http://stackoverflow.com/questions/2004843/software-development-methodology', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (72, 'acid properties', 'https://en.wikipedia.org/wiki/ACID', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (253, 'CSS Colors', 'http://www.w3schools.com/cssref/css_colors.asp', 'Different colors on CSS', 2, 'SV051339', 'Available');
INSERT INTO resource VALUES (74, 'this is a test resource', 'http://www.test.com', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (258, 'testtuesday', 'https://www.google.com/', 'testtuesday', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (88, 'git management', 'https://wiki.ucern.com/pages/viewpage.action?pageId=1046223965', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (263, 'testtuesday', 'https://www.google.com/', 'testtuesday', 3, 'SV051339', 'Available');
INSERT INTO resource VALUES (78, 'google', 'http://www.google.com', 'test_description', 4, 'SV051339', 'Available');
INSERT INTO resource VALUES (56, 'Testing', 'http://www.tutorialspoint.com/software_testing/', 'test_description', 2, 'SV051339', 'Available');
INSERT INTO resource VALUES (58, 'Spring Framework', 'http://www.tutorialspoint.com/spring/spring_web_mvc_framework.htm', 'test_description', 2, 'SV051339', 'Available');
INSERT INTO resource VALUES (71, 'Alter sql', 'http://docs.oracle.com/cd/B12037_01/server.101/b10759/statements_2011.htm#i2228022', 'test_description', 2, 'SV051339', 'Available');
INSERT INTO resource VALUES (73, 'garbage collection', 'http://www.oracle.com/webfolder/technetwork/tutorials/obe/java/gc01/index.html', 'test_description', 3, 'SV051339', 'Available');
INSERT INTO resource VALUES (79, 'yahoo', 'http://www.yahoo.co.in', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (85, 'abc', 'https://docs.oracle.com/javase/tutorial/jndi/ldap/result.html', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (89, 'Discount Page', 'https://connect.ucern.com/docs/DOC-228821', 'test_description', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (110, 'google', 'https://www.google.com/?gws_rd=ssl', 'Google link', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (105, 'google', 'http://www.googlerishi.com', 'ajasja', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (117, 'google', 'https://www.google.com/?gws_rd=ssl', 'google', 1, 'SV051339', 'Available');
INSERT INTO resource VALUES (126, 'google', 'https://www.google.com/?gws_rd=ssl', 'google link', 1, 'SV051339', 'Deleted');
INSERT INTO resource VALUES (129, 'google', 'https://www.google.com/?gws_rd=ssl', 'Google link', 1, 'SV051339', 'Deleted');
INSERT INTO resource VALUES (113, 'google', 'https://www.google.com/?gws_rd=ssl', 'google', 2, 'SV051339', 'Deleted');
INSERT INTO resource VALUES (116, 'google', 'https://www.google.com/?gws_rd=ssl', 'link', 1, 'SV051339', 'Deleted');
INSERT INTO resource VALUES (119, 'google', 'https://www.google.com/?gws_rd=ssl', 'google', 1, 'SV051339', 'Deleted');
INSERT INTO resource VALUES (127, 'google', 'https://www.google.com/?gws_rd=ssl', 'google link', 1, 'SV051339', 'Deleted');
INSERT INTO resource VALUES (130, 'google', 'https://www.google.com/?gws_rd=ssl', 'jdbc tutorial', 1, 'SV051339', 'Deleted');
INSERT INTO resource VALUES (128, 'google', 'https://www.google.com/?gws_rd=ssl', 'Google link', 1, 'SV051339', 'Deleted');
INSERT INTO resource VALUES (131, 'Wiki', 'https://en.wikipedia.org/wiki/CryptoLocker', 'Cryptolocker security issue', 2, 'SV051339', 'Deleted');
INSERT INTO resource VALUES (133, 'google', 'https://www.google.com/?gws_rd=ssl', 'Google link', 2, 'SV051339', 'Pending');
INSERT INTO resource VALUES (149, 'java', 'http://stackoverflow.com/questions/687833/how-to-get-the-last-value-of-an-arraylist', 'Stack Overflow', 3, 'SV051339', 'Pending');
INSERT INTO resource VALUES (152, 'linux', 'http://stackoverflow.com/questions/11839190/how-to-read-next-line-in-txt-file', 'Questions', 3, 'SV051339', 'Pending');
INSERT INTO resource VALUES (154, 'dot net', 'http://opencsv.sourceforge.net/', 'Apache ', 3, 'SV051339', 'Pending');
INSERT INTO resource VALUES (155, 'linux', 'http://stackoverflow.com/questions/11839190/how-to-read-next-line-in-txt-file', 'Questions', 3, 'SV051339', 'Pending');
INSERT INTO resource VALUES (52, 'Education', 'http://www.edu.com', 'test_description', 3, 'SV051339', 'Pending');
INSERT INTO resource VALUES (53, 'ASU', 'http://www.asu.edu', 'test_description', 3, 'SV051339', 'Pending');

-- Inserting data in topic_resource_reltn table
INSERT INTO topic_resource_reltn VALUES (210, 2, 1);
INSERT INTO topic_resource_reltn VALUES (215, 9, 1);
INSERT INTO topic_resource_reltn VALUES (215, 4, 1);
INSERT INTO topic_resource_reltn VALUES (217, 1, 1);
INSERT INTO topic_resource_reltn VALUES (258, 5, 1);
INSERT INTO topic_resource_reltn VALUES (259, 6, 1);
INSERT INTO topic_resource_reltn VALUES (222, 3, 1);
INSERT INTO topic_resource_reltn VALUES (224, 13, 1);
INSERT INTO topic_resource_reltn VALUES (225, 7, 1);
INSERT INTO topic_resource_reltn VALUES (226, 9, 1);
INSERT INTO topic_resource_reltn VALUES (226, 4, 1);
INSERT INTO topic_resource_reltn VALUES (228, 13, 1);
INSERT INTO topic_resource_reltn VALUES (230, 9, 1);
INSERT INTO topic_resource_reltn VALUES (230, 4, 1);
INSERT INTO topic_resource_reltn VALUES (232, 13, 1);
INSERT INTO topic_resource_reltn VALUES (234, 7, 1);
INSERT INTO topic_resource_reltn VALUES (237, 13, 1);
INSERT INTO topic_resource_reltn VALUES (239, 9, 1);
INSERT INTO topic_resource_reltn VALUES (239, 4, 1);
INSERT INTO topic_resource_reltn VALUES (240, 13, 1);
INSERT INTO topic_resource_reltn VALUES (241, 9, 1);
INSERT INTO topic_resource_reltn VALUES (241, 4, 1);
INSERT INTO topic_resource_reltn VALUES (243, 9, 1);
INSERT INTO topic_resource_reltn VALUES (58, 4, 2);
INSERT INTO topic_resource_reltn VALUES (243, 4, 1);
INSERT INTO topic_resource_reltn VALUES (260, 9, 1);
INSERT INTO topic_resource_reltn VALUES (261, 9, 1);
INSERT INTO topic_resource_reltn VALUES (61, 4, 2);
INSERT INTO topic_resource_reltn VALUES (244, 13, 1);
INSERT INTO topic_resource_reltn VALUES (262, 14, 1);
INSERT INTO topic_resource_reltn VALUES (63, 4, 2);
INSERT INTO topic_resource_reltn VALUES (69, 4, 2);
INSERT INTO topic_resource_reltn VALUES (69, 8, 2);
INSERT INTO topic_resource_reltn VALUES (69, 10, 2);
INSERT INTO topic_resource_reltn VALUES (72, 13, 2);
INSERT INTO topic_resource_reltn VALUES (73, 13, 2);
INSERT INTO topic_resource_reltn VALUES (263, 11, 1);
INSERT INTO topic_resource_reltn VALUES (264, 3, 2);
INSERT INTO topic_resource_reltn VALUES (79, 7, 2);
INSERT INTO topic_resource_reltn VALUES (85, 6, 2);
INSERT INTO topic_resource_reltn VALUES (52, 11, 2);
INSERT INTO topic_resource_reltn VALUES (52, 13, 2);
INSERT INTO topic_resource_reltn VALUES (94, 1, 2);
INSERT INTO topic_resource_reltn VALUES (95, 1, 2);
INSERT INTO topic_resource_reltn VALUES (96, 11, 2);
INSERT INTO topic_resource_reltn VALUES (98, 3, 2);
INSERT INTO topic_resource_reltn VALUES (53, 3, 2);
INSERT INTO topic_resource_reltn VALUES (53, 4, 2);
INSERT INTO topic_resource_reltn VALUES (101, 10, 2);
INSERT INTO topic_resource_reltn VALUES (53, 14, 2);
INSERT INTO topic_resource_reltn VALUES (55, 7, 2);
INSERT INTO topic_resource_reltn VALUES (56, 7, 2);
INSERT INTO topic_resource_reltn VALUES (120, 5, 2);
INSERT INTO topic_resource_reltn VALUES (120, 11, 2);
INSERT INTO topic_resource_reltn VALUES (121, 8, 2);
INSERT INTO topic_resource_reltn VALUES (121, 10, 2);
INSERT INTO topic_resource_reltn VALUES (151, 9, 3);
INSERT INTO topic_resource_reltn VALUES (151, 4, 3);
INSERT INTO topic_resource_reltn VALUES (154, 9, 3);
INSERT INTO topic_resource_reltn VALUES (154, 4, 3);
INSERT INTO topic_resource_reltn VALUES (245, 9, 1);
INSERT INTO topic_resource_reltn VALUES (245, 4, 1);
INSERT INTO topic_resource_reltn VALUES (161, 9, 3);
INSERT INTO topic_resource_reltn VALUES (161, 4, 3);
INSERT INTO topic_resource_reltn VALUES (164, 9, 3);
INSERT INTO topic_resource_reltn VALUES (164, 4, 3);
INSERT INTO topic_resource_reltn VALUES (167, 9, 3);
INSERT INTO topic_resource_reltn VALUES (167, 4, 3);
INSERT INTO topic_resource_reltn VALUES (170, 9, 3);
INSERT INTO topic_resource_reltn VALUES (170, 4, 3);
INSERT INTO topic_resource_reltn VALUES (246, 13, 1);
INSERT INTO topic_resource_reltn VALUES (175, 7, 3);
INSERT INTO topic_resource_reltn VALUES (176, 9, 3);
INSERT INTO topic_resource_reltn VALUES (176, 4, 3);
INSERT INTO topic_resource_reltn VALUES (193, 13, 1);
INSERT INTO topic_resource_reltn VALUES (194, 4, 1);
INSERT INTO topic_resource_reltn VALUES (196, 13, 1);
INSERT INTO topic_resource_reltn VALUES (197, 4, 1);
INSERT INTO topic_resource_reltn VALUES (199, 3, 2);
INSERT INTO topic_resource_reltn VALUES (200, 19, 2);
INSERT INTO topic_resource_reltn VALUES (201, 10, 1);
INSERT INTO topic_resource_reltn VALUES (205, 20, 1);
INSERT INTO topic_resource_reltn VALUES (208, 19, 1);
INSERT INTO topic_resource_reltn VALUES (209, 20, 1);
INSERT INTO topic_resource_reltn VALUES (248, 9, 1);
INSERT INTO topic_resource_reltn VALUES (248, 4, 1);
INSERT INTO topic_resource_reltn VALUES (249, 6, 1);
INSERT INTO topic_resource_reltn VALUES (251, 3, 4);
INSERT INTO topic_resource_reltn VALUES (251, 11, 4);
INSERT INTO topic_resource_reltn VALUES (251, 20, 3);
INSERT INTO topic_resource_reltn VALUES (252, 5, 1);
INSERT INTO topic_resource_reltn VALUES (253, 3, 4);
INSERT INTO topic_resource_reltn VALUES (253, 1, 2);
INSERT INTO topic_resource_reltn VALUES (254, 5, 1);
INSERT INTO topic_resource_reltn VALUES (256, 3, 4);
INSERT INTO topic_resource_reltn VALUES (256, 11, 5);
INSERT INTO topic_resource_reltn VALUES (257, 2, 4);
INSERT INTO topic_resource_reltn VALUES (257, 5, 4);
INSERT INTO topic_resource_reltn VALUES (257, 20, 1);
INSERT INTO topic_resource_reltn VALUES (26, 21, 2);
INSERT INTO topic_resource_reltn VALUES (2, 22, 2);
INSERT INTO topic_resource_reltn VALUES (6, 22, 2);
INSERT INTO topic_resource_reltn VALUES (7, 22, 2);
INSERT INTO topic_resource_reltn VALUES (8, 22, 2);
INSERT INTO topic_resource_reltn VALUES (9, 22, 2);
INSERT INTO topic_resource_reltn VALUES (10, 22, 2);
INSERT INTO topic_resource_reltn VALUES (12, 22, 2);
INSERT INTO topic_resource_reltn VALUES (13, 22, 2);
INSERT INTO topic_resource_reltn VALUES (14, 22, 2);
INSERT INTO topic_resource_reltn VALUES (16, 22, 2);
INSERT INTO topic_resource_reltn VALUES (17, 22, 2);
INSERT INTO topic_resource_reltn VALUES (18, 22, 2);
INSERT INTO topic_resource_reltn VALUES (19, 22, 2);
INSERT INTO topic_resource_reltn VALUES (20, 22, 2);
INSERT INTO topic_resource_reltn VALUES (22, 16, 2);
INSERT INTO topic_resource_reltn VALUES (24, 19, 2);
INSERT INTO topic_resource_reltn VALUES (151, 13, 3);
INSERT INTO topic_resource_reltn VALUES (152, 4, 3);
INSERT INTO topic_resource_reltn VALUES (154, 13, 3);
INSERT INTO topic_resource_reltn VALUES (155, 4, 3);
INSERT INTO topic_resource_reltn VALUES (210, 21, 1);
INSERT INTO topic_resource_reltn VALUES (159, 4, 3);
INSERT INTO topic_resource_reltn VALUES (161, 13, 3);
INSERT INTO topic_resource_reltn VALUES (162, 4, 3);
INSERT INTO topic_resource_reltn VALUES (164, 13, 3);
INSERT INTO topic_resource_reltn VALUES (165, 4, 3);
INSERT INTO topic_resource_reltn VALUES (167, 13, 3);
INSERT INTO topic_resource_reltn VALUES (168, 4, 3);
INSERT INTO topic_resource_reltn VALUES (215, 13, 1);
INSERT INTO topic_resource_reltn VALUES (121, 14, 2);
INSERT INTO topic_resource_reltn VALUES (125, 2, 2);
INSERT INTO topic_resource_reltn VALUES (125, 6, 2);
INSERT INTO topic_resource_reltn VALUES (125, 10, 2);
INSERT INTO topic_resource_reltn VALUES (130, 7, 2);
INSERT INTO topic_resource_reltn VALUES (133, 1, 2);
INSERT INTO topic_resource_reltn VALUES (216, 1, 1);
INSERT INTO topic_resource_reltn VALUES (217, 22, 1);
INSERT INTO topic_resource_reltn VALUES (224, 9, 1);
INSERT INTO topic_resource_reltn VALUES (224, 4, 1);
INSERT INTO topic_resource_reltn VALUES (225, 2, 1);
INSERT INTO topic_resource_reltn VALUES (226, 13, 1);
INSERT INTO topic_resource_reltn VALUES (228, 9, 1);
INSERT INTO topic_resource_reltn VALUES (228, 4, 1);
INSERT INTO topic_resource_reltn VALUES (230, 13, 1);
INSERT INTO topic_resource_reltn VALUES (232, 9, 1);
INSERT INTO topic_resource_reltn VALUES (232, 4, 1);
INSERT INTO topic_resource_reltn VALUES (237, 9, 1);
INSERT INTO topic_resource_reltn VALUES (237, 4, 1);
INSERT INTO topic_resource_reltn VALUES (239, 13, 1);
INSERT INTO topic_resource_reltn VALUES (240, 9, 1);
INSERT INTO topic_resource_reltn VALUES (240, 4, 1);
INSERT INTO topic_resource_reltn VALUES (241, 13, 1);
INSERT INTO topic_resource_reltn VALUES (242, 3, 3);
INSERT INTO topic_resource_reltn VALUES (243, 13, 1);
INSERT INTO topic_resource_reltn VALUES (170, 13, 3);
INSERT INTO topic_resource_reltn VALUES (171, 4, 3);
INSERT INTO topic_resource_reltn VALUES (244, 9, 1);
INSERT INTO topic_resource_reltn VALUES (244, 4, 1);
INSERT INTO topic_resource_reltn VALUES (175, 2, 3);
INSERT INTO topic_resource_reltn VALUES (176, 13, 3);
INSERT INTO topic_resource_reltn VALUES (177, 4, 3);
INSERT INTO topic_resource_reltn VALUES (193, 9, 1);
INSERT INTO topic_resource_reltn VALUES (193, 4, 1);
INSERT INTO topic_resource_reltn VALUES (196, 9, 1);
INSERT INTO topic_resource_reltn VALUES (196, 4, 1);
INSERT INTO topic_resource_reltn VALUES (199, 5, 3);
INSERT INTO topic_resource_reltn VALUES (201, 5, 1);
INSERT INTO topic_resource_reltn VALUES (201, 14, 1);
INSERT INTO topic_resource_reltn VALUES (205, 26, 1);
INSERT INTO topic_resource_reltn VALUES (208, 3, 1);
INSERT INTO topic_resource_reltn VALUES (209, 3, 1);
INSERT INTO topic_resource_reltn VALUES (245, 13, 1);
INSERT INTO topic_resource_reltn VALUES (246, 9, 1);
INSERT INTO topic_resource_reltn VALUES (246, 4, 1);
INSERT INTO topic_resource_reltn VALUES (248, 13, 1);
INSERT INTO topic_resource_reltn VALUES (249, 3, 1);
INSERT INTO topic_resource_reltn VALUES (250, 25, 1);
INSERT INTO topic_resource_reltn VALUES (251, 7, 3);
INSERT INTO topic_resource_reltn VALUES (251, 1, 4);
INSERT INTO topic_resource_reltn VALUES (252, 3, 4);
INSERT INTO topic_resource_reltn VALUES (252, 1, 2);
INSERT INTO topic_resource_reltn VALUES (253, 5, 1);
INSERT INTO topic_resource_reltn VALUES (254, 3, 4);
INSERT INTO topic_resource_reltn VALUES (254, 1, 2);
INSERT INTO topic_resource_reltn VALUES (256, 2, 4);
INSERT INTO topic_resource_reltn VALUES (256, 5, 4);
INSERT INTO topic_resource_reltn VALUES (256, 24, 1);
INSERT INTO topic_resource_reltn VALUES (257, 3, 4);
INSERT INTO topic_resource_reltn VALUES (257, 11, 5);
INSERT INTO topic_resource_reltn VALUES (258, 3, 1);
INSERT INTO topic_resource_reltn VALUES (259, 3, 1);
INSERT INTO topic_resource_reltn VALUES (260, 2, 1);
INSERT INTO topic_resource_reltn VALUES (261, 2, 1);
INSERT INTO topic_resource_reltn VALUES (262, 3, 1);
INSERT INTO topic_resource_reltn VALUES (263, 3, 1);
INSERT INTO topic_resource_reltn VALUES (263, 14, 1);
INSERT INTO topic_resource_reltn VALUES (264, 14, 2);
INSERT INTO topic_resource_reltn VALUES (1, 1, 1);
INSERT INTO topic_resource_reltn VALUES (21, 2, 2);
INSERT INTO topic_resource_reltn VALUES (27, 3, 3);
INSERT INTO topic_resource_reltn VALUES (28, 4, 4);
INSERT INTO topic_resource_reltn VALUES (29, 5, 5);
INSERT INTO topic_resource_reltn VALUES (30, 6, 1);
INSERT INTO topic_resource_reltn VALUES (31, 7, 2);
INSERT INTO topic_resource_reltn VALUES (45, 8, 3);
INSERT INTO topic_resource_reltn VALUES (46, 9, 4);
INSERT INTO topic_resource_reltn VALUES (49, 10, 5);
INSERT INTO topic_resource_reltn VALUES (71, 11, 1);
INSERT INTO topic_resource_reltn VALUES (74, 12, 2);
INSERT INTO topic_resource_reltn VALUES (78, 13, 3);
INSERT INTO topic_resource_reltn VALUES (88, 14, 4);
INSERT INTO topic_resource_reltn VALUES (89, 26, 5);
INSERT INTO topic_resource_reltn VALUES (102, 16, 1);
INSERT INTO topic_resource_reltn VALUES (103, 17, 2);
INSERT INTO topic_resource_reltn VALUES (104, 18, 3);
INSERT INTO topic_resource_reltn VALUES (105, 19, 4);
INSERT INTO topic_resource_reltn VALUES (106, 20, 5);
INSERT INTO topic_resource_reltn VALUES (107, 21, 1);
INSERT INTO topic_resource_reltn VALUES (108, 22, 2);
INSERT INTO topic_resource_reltn VALUES (109, 23, 3);
INSERT INTO topic_resource_reltn VALUES (110, 24, 4);
INSERT INTO topic_resource_reltn VALUES (111, 25, 5);
INSERT INTO topic_resource_reltn VALUES (112, 1, 1);
INSERT INTO topic_resource_reltn VALUES (113, 2, 2);
INSERT INTO topic_resource_reltn VALUES (114, 3, 3);
INSERT INTO topic_resource_reltn VALUES (115, 4, 4);
INSERT INTO topic_resource_reltn VALUES (116, 5, 5);
INSERT INTO topic_resource_reltn VALUES (117, 6, 1);
INSERT INTO topic_resource_reltn VALUES (119, 7, 2);
INSERT INTO topic_resource_reltn VALUES (126, 8, 3);
INSERT INTO topic_resource_reltn VALUES (127, 9, 4);
INSERT INTO topic_resource_reltn VALUES (128, 10, 5);
INSERT INTO topic_resource_reltn VALUES (129, 11, 1);
INSERT INTO topic_resource_reltn VALUES (131, 12, 2);
INSERT INTO topic_resource_reltn VALUES (132, 13, 3);
INSERT INTO topic_resource_reltn VALUES (149, 14, 4);
INSERT INTO topic_resource_reltn VALUES (156, 26, 5);
INSERT INTO topic_resource_reltn VALUES (186, 16, 1);
INSERT INTO topic_resource_reltn VALUES (188, 17, 2);
INSERT INTO topic_resource_reltn VALUES (189, 18, 3);
INSERT INTO topic_resource_reltn VALUES (190, 19, 4);
INSERT INTO topic_resource_reltn VALUES (211, 20, 5);
INSERT INTO topic_resource_reltn VALUES (218, 21, 1);
INSERT INTO topic_resource_reltn VALUES (219, 22, 2);

-- Inserting data in user_interested_topic table
INSERT INTO user_interested_topic VALUES ('GK045931', 21, 1, 3);
INSERT INTO user_interested_topic VALUES ('AM045300', 2, 1, 1);
INSERT INTO user_interested_topic VALUES ('AG045334', 2, 1, 1);
INSERT INTO user_interested_topic VALUES ('YG045907', 14, 3, 5);
INSERT INTO user_interested_topic VALUES ('YG045907', 26, 2, 5);
INSERT INTO user_interested_topic VALUES ('YG045907', 12, 4, 3);
INSERT INTO user_interested_topic VALUES ('YG045907', 25, 4, 5);
INSERT INTO user_interested_topic VALUES ('NP046332', 3, 1, 2);
INSERT INTO user_interested_topic VALUES ('AP045635', 2, 1, 1);
INSERT INTO user_interested_topic VALUES ('AP045635', 14, 1, 4);
INSERT INTO user_interested_topic VALUES ('GK045931', 4, 2, 1);
INSERT INTO user_interested_topic VALUES ('GK045931', 24, 2, 5);

-- Inserting data in tag table
ALTER SEQUENCE tag_tag_id_seq RESTART WITH 100;
INSERT INTO tag VALUES (1, 'test');
INSERT INTO tag VALUES (2, 'SQL');
INSERT INTO tag VALUES (3, 'maven');
INSERT INTO tag VALUES (4, 'Query');
INSERT INTO tag VALUES (5, 'postgres');
INSERT INTO tag VALUES (6, 'Output');
INSERT INTO tag VALUES (7, 'Data');
INSERT INTO tag VALUES (8, 'localhost');
INSERT INTO tag VALUES (9, 'cloud');

-- Inserting data in tag_resource_reltn table
INSERT INTO tag_resource_reltn VALUES (2, 263);
INSERT INTO tag_resource_reltn VALUES (5, 263);
INSERT INTO tag_resource_reltn VALUES (6, 263);

-- Inserting data in user_resource_rating table
INSERT INTO user_resource_rating VALUES ('GK045931', 125, 4);
INSERT INTO user_resource_rating VALUES ('GK045931', 175, 3);
INSERT INTO user_resource_rating VALUES ('GK045931', 256, 3);
INSERT INTO user_resource_rating VALUES ('GK045931', 151, 3);
INSERT INTO user_resource_rating VALUES ('GK045931', 69, 2);
INSERT INTO user_resource_rating VALUES ('GK045931', 58, 4);
INSERT INTO user_resource_rating VALUES ('GK045931', 120, 4);
INSERT INTO user_resource_rating VALUES ('GK045931', 199, 5);
INSERT INTO user_resource_rating VALUES ('GK045931', 201, 5);
INSERT INTO user_resource_rating VALUES ('GK045931', 252, 5);
INSERT INTO user_resource_rating VALUES ('GK045931', 251, 3);

-- Inserting data in user_interested_category table
INSERT INTO user_interested_category VALUES ('GK045931', 71, 1, 3);
INSERT INTO user_interested_category VALUES ('AM045300', 2, 1, 1);
INSERT INTO user_interested_category VALUES ('AG045334', 2, 1, 1);
INSERT INTO user_interested_category VALUES ('YG045907', 14, 3, 5);
INSERT INTO user_interested_category VALUES ('YG045907', 35, 2, 5);
INSERT INTO user_interested_category VALUES ('YG045907', 12, 4, 3);
INSERT INTO user_interested_category VALUES ('YG045907', 33, 4, 5);
INSERT INTO user_interested_category VALUES ('NP046332', 3, 1, 2);
INSERT INTO user_interested_category VALUES ('AP045635', 2, 1, 1);
INSERT INTO user_interested_category VALUES ('AP045635', 14, 1, 4);
INSERT INTO user_interested_category VALUES ('GK045931', 4, 2, 1);
INSERT INTO user_interested_category VALUES ('GK045931', 72, 2, 5);
INSERT INTO user_interested_category VALUES ('SK051343', 3, 2, 3);
INSERT INTO user_interested_category VALUES ('SK051343', 16, 1, 2);
INSERT INTO user_interested_category VALUES ('SK051343', 12, 2, 2);
INSERT INTO user_interested_category VALUES ('SK051343', 26, 1, 1);
INSERT INTO user_interested_category VALUES ('SK051343', 11, 1, 1);
INSERT INTO user_interested_category VALUES ('SK051343', 1, 1, 1);
INSERT INTO user_interested_category VALUES ('SK051343', 2, 1, 1);
INSERT INTO user_interested_category VALUES ('SK051343', 18, 1, 1);
INSERT INTO user_interested_category VALUES ('SK051343', 13, 3, 3);
INSERT INTO user_interested_category VALUES ('SK051343', 10, 1, 1);


-- Inserting data in category_resource_reltn table
INSERT INTO category_resource_reltn VALUES (210, 2, 1);
INSERT INTO category_resource_reltn VALUES (215, 9, 1);
INSERT INTO category_resource_reltn VALUES (215, 4, 1);
INSERT INTO category_resource_reltn VALUES (217, 1, 1);
INSERT INTO category_resource_reltn VALUES (258, 5, 1);
INSERT INTO category_resource_reltn VALUES (259, 6, 1);
INSERT INTO category_resource_reltn VALUES (222, 3, 1);
INSERT INTO category_resource_reltn VALUES (224, 13, 1);
INSERT INTO category_resource_reltn VALUES (225, 7, 1);
INSERT INTO category_resource_reltn VALUES (226, 9, 1);
INSERT INTO category_resource_reltn VALUES (226, 4, 1);
INSERT INTO category_resource_reltn VALUES (228, 13, 1);
INSERT INTO category_resource_reltn VALUES (230, 9, 1);
INSERT INTO category_resource_reltn VALUES (230, 4, 1);
INSERT INTO category_resource_reltn VALUES (232, 13, 1);
INSERT INTO category_resource_reltn VALUES (234, 7, 1);
INSERT INTO category_resource_reltn VALUES (237, 13, 1);
INSERT INTO category_resource_reltn VALUES (239, 9, 1);
INSERT INTO category_resource_reltn VALUES (239, 4, 1);
INSERT INTO category_resource_reltn VALUES (240, 13, 1);
INSERT INTO category_resource_reltn VALUES (241, 9, 1);
INSERT INTO category_resource_reltn VALUES (241, 4, 1);
INSERT INTO category_resource_reltn VALUES (243, 9, 1);
INSERT INTO category_resource_reltn VALUES (58, 4, 2);
INSERT INTO category_resource_reltn VALUES (243, 4, 1);
INSERT INTO category_resource_reltn VALUES (260, 9, 1);
INSERT INTO category_resource_reltn VALUES (261, 9, 1);
INSERT INTO category_resource_reltn VALUES (61, 4, 2);
INSERT INTO category_resource_reltn VALUES (244, 13, 1);
INSERT INTO category_resource_reltn VALUES (262, 14, 1);
INSERT INTO category_resource_reltn VALUES (63, 4, 2);
INSERT INTO category_resource_reltn VALUES (69, 4, 2);
INSERT INTO category_resource_reltn VALUES (69, 8, 2);
INSERT INTO category_resource_reltn VALUES (69, 10, 2);
INSERT INTO category_resource_reltn VALUES (72, 13, 2);
INSERT INTO category_resource_reltn VALUES (73, 13, 2);
INSERT INTO category_resource_reltn VALUES (263, 11, 1);
INSERT INTO category_resource_reltn VALUES (264, 3, 2);
INSERT INTO category_resource_reltn VALUES (79, 7, 2);
INSERT INTO category_resource_reltn VALUES (85, 6, 2);
INSERT INTO category_resource_reltn VALUES (52, 11, 2);
INSERT INTO category_resource_reltn VALUES (52, 13, 2);
INSERT INTO category_resource_reltn VALUES (94, 1, 2);
INSERT INTO category_resource_reltn VALUES (95, 1, 2);
INSERT INTO category_resource_reltn VALUES (96, 11, 2);
INSERT INTO category_resource_reltn VALUES (98, 3, 2);
INSERT INTO category_resource_reltn VALUES (53, 3, 2);
INSERT INTO category_resource_reltn VALUES (53, 4, 2);
INSERT INTO category_resource_reltn VALUES (101, 10, 2);
INSERT INTO category_resource_reltn VALUES (53, 15, 2);
INSERT INTO category_resource_reltn VALUES (55, 7, 2);
INSERT INTO category_resource_reltn VALUES (56, 7, 2);
INSERT INTO category_resource_reltn VALUES (120, 5, 2);
INSERT INTO category_resource_reltn VALUES (120, 11, 2);
INSERT INTO category_resource_reltn VALUES (121, 8, 2);
INSERT INTO category_resource_reltn VALUES (121, 10, 2);
INSERT INTO category_resource_reltn VALUES (151, 9, 3);
INSERT INTO category_resource_reltn VALUES (151, 4, 3);
INSERT INTO category_resource_reltn VALUES (154, 9, 3);
INSERT INTO category_resource_reltn VALUES (154, 4, 3);
INSERT INTO category_resource_reltn VALUES (245, 9, 1);
INSERT INTO category_resource_reltn VALUES (245, 4, 1);
INSERT INTO category_resource_reltn VALUES (161, 9, 3);
INSERT INTO category_resource_reltn VALUES (161, 4, 3);
INSERT INTO category_resource_reltn VALUES (164, 9, 3);
INSERT INTO category_resource_reltn VALUES (164, 4, 3);
INSERT INTO category_resource_reltn VALUES (167, 9, 3);
INSERT INTO category_resource_reltn VALUES (167, 4, 3);
INSERT INTO category_resource_reltn VALUES (170, 9, 3);
INSERT INTO category_resource_reltn VALUES (170, 4, 3);
INSERT INTO category_resource_reltn VALUES (246, 13, 1);
INSERT INTO category_resource_reltn VALUES (175, 7, 3);
INSERT INTO category_resource_reltn VALUES (176, 9, 3);
INSERT INTO category_resource_reltn VALUES (176, 4, 3);
INSERT INTO category_resource_reltn VALUES (179, 7, 1);
INSERT INTO category_resource_reltn VALUES (180, 9, 1);
INSERT INTO category_resource_reltn VALUES (180, 4, 1);
INSERT INTO category_resource_reltn VALUES (184, 3, 1);
INSERT INTO category_resource_reltn VALUES (193, 13, 1);
INSERT INTO category_resource_reltn VALUES (194, 4, 1);
INSERT INTO category_resource_reltn VALUES (196, 13, 1);
INSERT INTO category_resource_reltn VALUES (197, 4, 1);
INSERT INTO category_resource_reltn VALUES (199, 3, 2);
INSERT INTO category_resource_reltn VALUES (200, 45, 2);
INSERT INTO category_resource_reltn VALUES (201, 10, 1);
INSERT INTO category_resource_reltn VALUES (205, 35, 1);
INSERT INTO category_resource_reltn VALUES (208, 42, 1);
INSERT INTO category_resource_reltn VALUES (209, 42, 1);
INSERT INTO category_resource_reltn VALUES (248, 9, 1);
INSERT INTO category_resource_reltn VALUES (248, 4, 1);
INSERT INTO category_resource_reltn VALUES (249, 6, 1);
INSERT INTO category_resource_reltn VALUES (251, 3, 4);
INSERT INTO category_resource_reltn VALUES (251, 11, 4);
INSERT INTO category_resource_reltn VALUES (251, 39, 3);
INSERT INTO category_resource_reltn VALUES (252, 5, 1);
INSERT INTO category_resource_reltn VALUES (253, 3, 4);
INSERT INTO category_resource_reltn VALUES (253, 1, 2);
INSERT INTO category_resource_reltn VALUES (254, 5, 1);
INSERT INTO category_resource_reltn VALUES (256, 3, 4);
INSERT INTO category_resource_reltn VALUES (256, 11, 5);
INSERT INTO category_resource_reltn VALUES (257, 2, 4);
INSERT INTO category_resource_reltn VALUES (257, 5, 4);
INSERT INTO category_resource_reltn VALUES (257, 33, 1);
INSERT INTO category_resource_reltn VALUES (26, 71, 2);
INSERT INTO category_resource_reltn VALUES (43, 71, 2);
INSERT INTO category_resource_reltn VALUES (43, 71, 2);
INSERT INTO category_resource_reltn VALUES (2, 72, 2);
INSERT INTO category_resource_reltn VALUES (6, 72, 2);
INSERT INTO category_resource_reltn VALUES (7, 72, 2);
INSERT INTO category_resource_reltn VALUES (8, 72, 2);
INSERT INTO category_resource_reltn VALUES (9, 72, 2);
INSERT INTO category_resource_reltn VALUES (10, 72, 2);
INSERT INTO category_resource_reltn VALUES (12, 72, 2);
INSERT INTO category_resource_reltn VALUES (13, 72, 2);
INSERT INTO category_resource_reltn VALUES (14, 72, 2);
INSERT INTO category_resource_reltn VALUES (16, 72, 2);
INSERT INTO category_resource_reltn VALUES (17, 72, 2);
INSERT INTO category_resource_reltn VALUES (18, 72, 2);
INSERT INTO category_resource_reltn VALUES (19, 72, 2);
INSERT INTO category_resource_reltn VALUES (20, 72, 2);
INSERT INTO category_resource_reltn VALUES (22, 72, 2);
INSERT INTO category_resource_reltn VALUES (24, 72, 2);
INSERT INTO category_resource_reltn VALUES (151, 13, 3);
INSERT INTO category_resource_reltn VALUES (152, 4, 3);
INSERT INTO category_resource_reltn VALUES (154, 13, 3);
INSERT INTO category_resource_reltn VALUES (155, 4, 3);
INSERT INTO category_resource_reltn VALUES (210, 39, 1);
INSERT INTO category_resource_reltn VALUES (159, 4, 3);
INSERT INTO category_resource_reltn VALUES (161, 13, 3);
INSERT INTO category_resource_reltn VALUES (162, 4, 3);
INSERT INTO category_resource_reltn VALUES (164, 13, 3);
INSERT INTO category_resource_reltn VALUES (165, 4, 3);
INSERT INTO category_resource_reltn VALUES (167, 13, 3);
INSERT INTO category_resource_reltn VALUES (168, 4, 3);
INSERT INTO category_resource_reltn VALUES (215, 13, 1);
INSERT INTO category_resource_reltn VALUES (121, 14, 2);
INSERT INTO category_resource_reltn VALUES (125, 2, 2);
INSERT INTO category_resource_reltn VALUES (125, 6, 2);
INSERT INTO category_resource_reltn VALUES (125, 10, 2);
INSERT INTO category_resource_reltn VALUES (130, 7, 2);
INSERT INTO category_resource_reltn VALUES (133, 1, 2);
INSERT INTO category_resource_reltn VALUES (134, 4, 2);
INSERT INTO category_resource_reltn VALUES (135, 4, 2);
INSERT INTO category_resource_reltn VALUES (136, 4, 2);
INSERT INTO category_resource_reltn VALUES (137, 4, 2);
INSERT INTO category_resource_reltn VALUES (138, 4, 2);
INSERT INTO category_resource_reltn VALUES (139, 4, 2);
INSERT INTO category_resource_reltn VALUES (140, 4, 2);
INSERT INTO category_resource_reltn VALUES (141, 4, 2);
INSERT INTO category_resource_reltn VALUES (142, 4, 2);
INSERT INTO category_resource_reltn VALUES (143, 4, 2);
INSERT INTO category_resource_reltn VALUES (144, 4, 2);
INSERT INTO category_resource_reltn VALUES (216, 1, 1);
INSERT INTO category_resource_reltn VALUES (217, 42, 1);
INSERT INTO category_resource_reltn VALUES (224, 9, 1);
INSERT INTO category_resource_reltn VALUES (224, 4, 1);
INSERT INTO category_resource_reltn VALUES (225, 2, 1);
INSERT INTO category_resource_reltn VALUES (226, 13, 1);
INSERT INTO category_resource_reltn VALUES (228, 9, 1);
INSERT INTO category_resource_reltn VALUES (228, 4, 1);
INSERT INTO category_resource_reltn VALUES (230, 13, 1);
INSERT INTO category_resource_reltn VALUES (232, 9, 1);
INSERT INTO category_resource_reltn VALUES (232, 4, 1);
INSERT INTO category_resource_reltn VALUES (237, 9, 1);
INSERT INTO category_resource_reltn VALUES (237, 4, 1);
INSERT INTO category_resource_reltn VALUES (239, 13, 1);
INSERT INTO category_resource_reltn VALUES (240, 9, 1);
INSERT INTO category_resource_reltn VALUES (240, 4, 1);
INSERT INTO category_resource_reltn VALUES (241, 13, 1);
INSERT INTO category_resource_reltn VALUES (242, 3, 3);
INSERT INTO category_resource_reltn VALUES (243, 13, 1);
INSERT INTO category_resource_reltn VALUES (170, 13, 3);
INSERT INTO category_resource_reltn VALUES (171, 4, 3);
INSERT INTO category_resource_reltn VALUES (244, 9, 1);
INSERT INTO category_resource_reltn VALUES (244, 4, 1);
INSERT INTO category_resource_reltn VALUES (175, 2, 3);
INSERT INTO category_resource_reltn VALUES (176, 13, 3);
INSERT INTO category_resource_reltn VALUES (177, 4, 3);
INSERT INTO category_resource_reltn VALUES (179, 2, 1);
INSERT INTO category_resource_reltn VALUES (180, 13, 1);
INSERT INTO category_resource_reltn VALUES (181, 4, 1);
INSERT INTO category_resource_reltn VALUES (193, 9, 1);
INSERT INTO category_resource_reltn VALUES (193, 4, 1);
INSERT INTO category_resource_reltn VALUES (196, 9, 1);
INSERT INTO category_resource_reltn VALUES (196, 4, 1);
INSERT INTO category_resource_reltn VALUES (199, 5, 3);
INSERT INTO category_resource_reltn VALUES (201, 5, 1);
INSERT INTO category_resource_reltn VALUES (201, 14, 1);
INSERT INTO category_resource_reltn VALUES (205, 33, 1);
INSERT INTO category_resource_reltn VALUES (208, 3, 1);
INSERT INTO category_resource_reltn VALUES (209, 3, 1);
INSERT INTO category_resource_reltn VALUES (245, 13, 1);
INSERT INTO category_resource_reltn VALUES (246, 9, 1);
INSERT INTO category_resource_reltn VALUES (246, 4, 1);
INSERT INTO category_resource_reltn VALUES (248, 13, 1);
INSERT INTO category_resource_reltn VALUES (249, 3, 1);
INSERT INTO category_resource_reltn VALUES (250, 42, 1);
INSERT INTO category_resource_reltn VALUES (251, 7, 3);
INSERT INTO category_resource_reltn VALUES (251, 1, 4);
INSERT INTO category_resource_reltn VALUES (252, 3, 4);
INSERT INTO category_resource_reltn VALUES (252, 1, 2);
INSERT INTO category_resource_reltn VALUES (253, 5, 1);
INSERT INTO category_resource_reltn VALUES (254, 3, 4);
INSERT INTO category_resource_reltn VALUES (254, 1, 2);
INSERT INTO category_resource_reltn VALUES (256, 2, 4);
INSERT INTO category_resource_reltn VALUES (256, 5, 4);
INSERT INTO category_resource_reltn VALUES (256, 33, 1);
INSERT INTO category_resource_reltn VALUES (257, 3, 4);
INSERT INTO category_resource_reltn VALUES (257, 11, 5);
INSERT INTO category_resource_reltn VALUES (258, 3, 1);
INSERT INTO category_resource_reltn VALUES (259, 3, 1);
INSERT INTO category_resource_reltn VALUES (260, 2, 1);
INSERT INTO category_resource_reltn VALUES (261, 2, 1);
INSERT INTO category_resource_reltn VALUES (262, 3, 1);
INSERT INTO category_resource_reltn VALUES (263, 3, 1);
INSERT INTO category_resource_reltn VALUES (263, 14, 1);
INSERT INTO category_resource_reltn VALUES (264, 39, 2);

-- Privilage commands
REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;










